name: flutter_petrel
description: "用于Flutter的热更新"
version: 0.0.3
# resolution: workspace

environment:
  sdk: ^3.5.4
  flutter: ">=3.24.5"

dependencies:
  appwrite: ^15.0.0
  archive: ^4.0.5
  darty_json_safe: ^1.0.3
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  get: ^4.7.2
  path: ^1.9.0
  path_provider: ^2.1.5
  petrel: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
